sonar.projectKey=fabriciosantana_poo
sonar.organization=fabriciosantana
sonar.sources=.
sonar.inclusions=**/*.java
sonar.java.binaries=.sonar-binaries/**,**/target/classes
# Ignora pastas que não serão compiladas pelo pipeline
sonar.exclusions=**/*.class
